name: Weekly Schedule Update

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # Use pip caching for dependencies

      - name: Set up Python Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Parsers
        run: |
          ./venv/bin/python parse_mewa.py
          ./venv/bin/python parse_delfin.py
          ./venv/bin/python parse_olimpijczyk.py

      - name: Run Aggregator
        run: ./venv/bin/python master_aggregator.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
          commit_message: 'Update pool schedules'